### ISSUE TITLE
How do I fix this error on Windows?

### ISSUE THREAD

**Issue by FaultyFunctions** [Konstanius/MineCICD#16]
```console
[23:14:13 ERROR]: [MineCICD] Failed to check for changes
[23:14:13 ERROR]: [MineCICD] Exception caught during execution of add command
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
        at MineCICD-2.2.1.jar/org.eclipse.jgit.api.AddCommand.call(AddCommand.java:225) ~[MineCICD-2.2.1.jar:?]
        at MineCICD-2.2.1.jar/ml.konstanius.minecicd.GitUtils.getLocalChanges(GitUtils.java:242) ~[MineCICD-2.2.1.jar:?]
        at MineCICD-2.2.1.jar/ml.konstanius.minecicd.BaseCommand.lambda$onCommand$0(BaseCommand.java:608) ~[MineCICD-2.2.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
        at java.base/java.io.FileInputStream.read0(Native Method) ~[?:?]
        at java.base/java.io.FileInputStream.read(FileInputStream.java:231) ~[?:?]
        at MineCICD-2.2.1.jar/org.eclipse.jgit.util.IO.readWholeStream(IO.java:169) ~[MineCICD-2.2.1.jar:?]
        at MineCICD-2.2.1.jar/org.eclipse.jgit.treewalk.WorkingTreeIterator.possiblyFilteredInputStream(WorkingTreeIterator.java:418) ~[MineCICD-2.2.1.jar:?]
        at MineCICD-2.2.1.jar/org.eclipse.jgit.treewalk.WorkingTreeIterator.possiblyFilteredInputStream(WorkingTreeIterator.java:404) ~[MineCICD-2.2.1.jar:?]
        at MineCICD-2.2.1.jar/org.eclipse.jgit.treewalk.WorkingTreeIterator.getEntryContentLength(WorkingTreeIterator.java:617) ~[MineCICD-2.2.1.jar:?]
        at MineCICD-2.2.1.jar/org.eclipse.jgit.api.AddCommand.call(AddCommand.java:200) ~[MineCICD-2.2.1.jar:?]
        ... 8 more
[23:14:13 ERROR]: [MineCICD] MineCICD-2.2.1.jar//org.eclipse.jgit.api.AddCommand.call(AddCommand.java:225)
MineCICD-2.2.1.jar//ml.konstanius.minecicd.GitUtils.getLocalChanges(GitUtils.java:242)
MineCICD-2.2.1.jar//ml.konstanius.minecicd.BaseCommand.lambda$onCommand$0(BaseCommand.java:608)
org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
java.base/java.lang.Thread.run(Thread.java:1583)

[23:14:13 WARN]: [MineCICD] Plugin MineCICD v2.2.1 generated an exception while executing task 1241
java.lang.IllegalStateException: Failed to check for changes
        at MineCICD-2.2.1.jar/ml.konstanius.minecicd.GitUtils.getLocalChanges(GitUtils.java:247) ~[MineCICD-2.2.1.jar:?]
        at MineCICD-2.2.1.jar/ml.konstanius.minecicd.BaseCommand.lambda$onCommand$0(BaseCommand.java:608) ~[MineCICD-2.2.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

It happens whenever I do basically any mineCICD command. It doesn't happen on my linux server.

**Comment by Konstanius** [comment]
Please share which other plugins you have installed and what your server software is.

**Comment by FaultyFunctions** [comment]
I am running purpur-1.21.1-2329.

I have quite a few plugins:
![image](https://github.com/user-attachments/assets/a79012d8-2843-44a7-860a-a804237260c6)
![image](https://github.com/user-attachments/assets/031dd1a5-687b-4947-8ad2-e0dd61334d46)
![image](https://github.com/user-attachments/assets/631ce00c-d88b-4db4-803c-62ac5389fe45)

When I get a chance I will test it on a clean server on windows and get back to you.

**Comment by Konstanius** [comment]
Please try with less plugins, debugging 72 other plugins will take ages. If you identify the plugin, please do tell.
I could, in the future, include a check and retry / debounce system for locked files.
