### ISSUE TITLE
Error when pulling from a repo

### ISSUE THREAD

**Issue by Zekariaa** [Konstanius/MineCICD#8]
Hello! Hope you are doing well. Thanks for the amazing plugin! 
I am encountering an error when doing /minecicd pull force.
```
[14:50:51 INFO]: Zekaria issued server command: /minecicd pull force
[14:50:51 ERROR]: [MineCICD] Failed to check for changes
[14:50:51 ERROR]: [MineCICD] Exception caught during execution of add command
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
        at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:225) ~[MineCICD-2.1.2.jar:?]
        at ml.konstanius.minecicd.GitUtils.getLocalChanges(GitUtils.java:222) ~[MineCICD-2.1.2.jar:?]
        at ml.konstanius.minecicd.BaseCommand.lambda$onCommand$0(BaseCommand.java:195) ~[MineCICD-2.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[?:git-UniverseSpigot-"72525e9"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[?:git-UniverseSpigot-"72525e9"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[?:git-UniverseSpigot-"72525e9"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /home/container/.git/index. Ensure that no other process has an open file handle on the lock file /home/container/.git/index.lock, then you may delete the lock file and retry.
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:222) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:293) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:259) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1282) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:122) ~[MineCICD-2.1.2.jar:?]
        ... 8 more
[14:50:51 ERROR]: [MineCICD] MineCICD-2.1.2.jar//org.eclipse.jgit.api.AddCommand.call(AddCommand.java:225)
MineCICD-2.1.2.jar//ml.konstanius.minecicd.GitUtils.getLocalChanges(GitUtils.java:222)
MineCICD-2.1.2.jar//ml.konstanius.minecicd.BaseCommand.lambda$onCommand$0(BaseCommand.java:195)
org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100)
org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
java.base/java.lang.Thread.run(Thread.java:1583)
[14:50:51 WARN]: [MineCICD] Plugin MineCICD v2.0 generated an exception while executing task 1011404
java.lang.IllegalStateException: Failed to check for changes
        at ml.konstanius.minecicd.GitUtils.getLocalChanges(GitUtils.java:227) ~[MineCICD-2.1.2.jar:?]
        at ml.konstanius.minecicd.BaseCommand.lambda$onCommand$0(BaseCommand.java:195) ~[MineCICD-2.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[?:git-UniverseSpigot-"72525e9"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[?:git-UniverseSpigot-"72525e9"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[?:git-UniverseSpigot-"72525e9"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:51:03 INFO]: Zekaria issued server command: /minecicd pull force
[14:51:03 ERROR]: [MineCICD] Failed to check for changes
[14:51:03 ERROR]: [MineCICD] Exception caught during execution of add command
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
        at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:225) ~[MineCICD-2.1.2.jar:?]
        at ml.konstanius.minecicd.GitUtils.getLocalChanges(GitUtils.java:222) ~[MineCICD-2.1.2.jar:?]
        at ml.konstanius.minecicd.BaseCommand.lambda$onCommand$0(BaseCommand.java:195) ~[MineCICD-2.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[?:git-UniverseSpigot-"72525e9"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[?:git-UniverseSpigot-"72525e9"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[?:git-UniverseSpigot-"72525e9"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /home/container/.git/index. Ensure that no other process has an open file handle on the lock file /home/container/.git/index.lock, then you may delete the lock file and retry.
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:222) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:293) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:259) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1282) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:122) ~[MineCICD-2.1.2.jar:?]
        ... 8 more
[14:51:03 ERROR]: [MineCICD] MineCICD-2.1.2.jar//org.eclipse.jgit.api.AddCommand.call(AddCommand.java:225)
MineCICD-2.1.2.jar//ml.konstanius.minecicd.GitUtils.getLocalChanges(GitUtils.java:222)
MineCICD-2.1.2.jar//ml.konstanius.minecicd.BaseCommand.lambda$onCommand$0(BaseCommand.java:195)
org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100)
org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
java.base/java.lang.Thread.run(Thread.java:1583)
[14:51:03 WARN]: [MineCICD] Plugin MineCICD v2.0 generated an exception while executing task 1012043
java.lang.IllegalStateException: Failed to check for changes
        at ml.konstanius.minecicd.GitUtils.getLocalChanges(GitUtils.java:227) ~[MineCICD-2.1.2.jar:?]
        at ml.konstanius.minecicd.BaseCommand.lambda$onCommand$0(BaseCommand.java:195) ~[MineCICD-2.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[?:git-UniverseSpigot-"72525e9"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[?:git-UniverseSpigot-"72525e9"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[?:git-UniverseSpigot-"72525e9"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:51:04 INFO]: Zekaria issued server command: /minecicd pull
[14:51:04 ERROR]: [MineCICD] Failed to check for changes
[14:51:04 ERROR]: [MineCICD] Exception caught during execution of add command
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
        at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:225) ~[MineCICD-2.1.2.jar:?]
        at ml.konstanius.minecicd.GitUtils.getLocalChanges(GitUtils.java:222) ~[MineCICD-2.1.2.jar:?]
        at ml.konstanius.minecicd.BaseCommand.lambda$onCommand$0(BaseCommand.java:195) ~[MineCICD-2.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[?:git-UniverseSpigot-"72525e9"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[?:git-UniverseSpigot-"72525e9"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[?:git-UniverseSpigot-"72525e9"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /home/container/.git/index. Ensure that no other process has an open file handle on the lock file /home/container/.git/index.lock, then you may delete the lock file and retry.
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:222) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:293) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:259) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1282) ~[MineCICD-2.1.2.jar:?]
        at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:122) ~[MineCICD-2.1.2.jar:?]
        ... 8 more
[14:51:04 ERROR]: [MineCICD] MineCICD-2.1.2.jar//org.eclipse.jgit.api.AddCommand.call(AddCommand.java:225)
MineCICD-2.1.2.jar//ml.konstanius.minecicd.GitUtils.getLocalChanges(GitUtils.java:222)
MineCICD-2.1.2.jar//ml.konstanius.minecicd.BaseCommand.lambda$onCommand$0(BaseCommand.java:195)
org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100)
org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
java.base/java.lang.Thread.run(Thread.java:1583)
[14:51:04 WARN]: [MineCICD] Plugin MineCICD v2.0 generated an exception while executing task 1012231
java.lang.IllegalStateException: Failed to check for changes
```
Do you have any idea of why it is spawning?

**Comment by Konstanius** [comment]
Please follow these steps to try and fix the problem:

1. Restart the server
2. Run /minecicd resolve repo-reset
3. Restart the server again
4. Run /minecicd pull

If that hasnt fixed the issue, please send additional information as follows:

- Your operating system
- Your Server Jarfile Version (and Make)
- Are you self hosting this, or are you using a control panel? If so, which?
